In [170]:
#The overview tab in the userinterface uses a list of the dates where there is one record for each date
#This file was structured with the following codes in this notebook
import pandas as pd
import datetime

events = pd.read_csv("event_infos.csv",",")
dates = events["Starting_datetime"]
date_to_add = []
starting_hours = []
ending_dates = events["Ending_datetime"]
ending_dates = pd.to_datetime(ending_dates)
ending_hours= []
dates = pd.to_datetime(dates)

for d in dates:
    date_to_add.append(d.date())   
    starting_hours.append(d.time().strftime("%H:%M"))

for d in ending_dates:
    ending_hours.append(d.time().strftime("%H:%M"))

events["Date"] = date_to_add
events["Starting hour"] = starting_hours
events["Ending hour"] = ending_hours

/Users/annalorincz/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3444: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)

In [171]:
events = events[events["Date"]>=datetime.date(2020,1,1)]
events["Starting_datetime"] = pd.to_datetime(events["Starting_datetime"])
events.sort_values(by="Starting_datetime", inplace =True)

event_dates = list(events["Date"])
event_number = []
event_number.append(1)
e=1
for i in range(1,len(events)):
    if event_dates[i] != event_dates[i-1]:
        e = 1
        event_number.append(e)
    elif event_dates[i] == event_dates[i-1]:
        e += 1
        event_number.append(e)
events["Number on day"]  =   event_number

In [177]:

event1 = events[events["Number on day"] == 1][["Titel", "Evenementlocatie", "Starting hour", "Ending hour", "BezoekersVerwacht", "Date"]]
event1.rename(columns={"Titel": "Event 1 - Titel", "Evenementlocatie": "Event 1 - Location", "Starting hour": "Event 1 - Starting hour","Ending hour":"Event 1- Ending hour", "BezoekersVerwacht": "Event 1 - Expected visitros", "Date":"Time_to_filter"}, inplace = True)
event1["Time_to_filter"] = pd.to_datetime(event1["Time_to_filter"])

event2 = events[events["Number on day"] == 2][["Titel", "Evenementlocatie", "Starting hour", "Ending hour", "BezoekersVerwacht", "Date"]]
event2.rename(columns={"Titel": "Event 2 - Titel", "Evenementlocatie": "Event 2 - Location", "Starting hour": "Event 2 - Starting hour","Ending hour":"Event 2- Ending hour", "BezoekersVerwacht": "Event 2 - Expected visitros" , "Date":"Time_to_filter"}, inplace = True)
event2["Time_to_filter"] = pd.to_datetime(event2["Time_to_filter"])

event3 = events[events["Number on day"] == 3][["Titel", "Evenementlocatie", "Starting hour", "Ending hour", "BezoekersVerwacht", "Date"]]
event3.rename(columns={"Titel": "Event 3 - Titel", "Evenementlocatie": "Event 3 - Location", "Starting hour": "Event 3 - Starting hour","Ending hour":"Event 3- Ending hour", "BezoekersVerwacht": "Event 3 - Expected visitros", "Date":"Time_to_filter" }, inplace = True)
event3["Time_to_filter"] = pd.to_datetime(event3["Time_to_filter"])

event4 = events[events["Number on day"] == 4][["Titel", "Evenementlocatie", "Starting hour", "Ending hour", "BezoekersVerwacht", "Date"]]
event4.rename(columns={"Titel": "Event 4 - Titel", "Evenementlocatie": "Event 4 - Location", "Starting hour": "Event 4 - Starting hour","Ending hour":"Event 4- Ending hour", "BezoekersVerwacht": "Event 4 - Expected visitros", "Date":"Time_to_filter" }, inplace = True)
event4["Time_to_filter"] = pd.to_datetime(event4["Time_to_filter"])

In [179]:
time_range = pd.date_range('2020-01-01T0:00', '2021-12-26T0:00', freq = 'D')

events_to_display = pd.DataFrame(columns = ['Time_to_filter'])
events_to_display["Time_to_filter"] = time_range

    Time_to_filter
0       2020-01-01
1       2020-01-02
2       2020-01-03
3       2020-01-04
4       2020-01-05
..             ...
721     2021-12-22
722     2021-12-23
723     2021-12-24
724     2021-12-25
725     2021-12-26

[726 rows x 1 columns]

In [180]:
events_to_display = events_to_display.merge(event1, how="left", left_on="Time_to_filter", right_on="Time_to_filter")
events_to_display = events_to_display.merge(event2, how="left", left_on="Time_to_filter", right_on="Time_to_filter")
events_to_display = events_to_display.merge(event3, how="left", left_on="Time_to_filter", right_on="Time_to_filter")
events_to_display = events_to_display.merge(event4, how="left", left_on="Time_to_filter", right_on="Time_to_filter")

In [184]:
events_to_display["Time_to_filter"] = pd.to_datetime(events_to_display["Time_to_filter"])
events_to_display["Time_to_filter"] = [i.date() for i in events_to_display["Time_to_filter"]]
events_to_display[events_to_display["Time_to_filter"] == datetime.date(2020,7,18)]

,Time_to_filter,Event 1 - Titel,Event 1 - Location,Event 1 - Starting hour,Event 1- Ending hour,Event 1 - Expected visitros,Event 2 - Titel,Event 2 - Location,Event 2 - Starting hour,Event 2- Ending hour,...,Event 3 - Titel,Event 3 - Location,Event 3 - Starting hour,Event 3- Ending hour,Event 3 - Expected visitros,Event 4 - Titel,Event 4 - Location,Event 4 - Starting hour,Event 4- Ending hour,Event 4 - Expected visitros
199,2020-07-18,"Restaurant ""Langs de Lijn""",Johan Cruijff ArenA,18:30,22:30,100.0,Dennis van Aarssen (huiskamerconcert),AFAS Live,19:00,20:30,...,Dennis van Aarssen (huiskamerconcert),AFAS Live,21:30,23:00,100.0,NaN,NaN,NaN,NaN,NaN

In [182]:
events_to_display

In [185]:
events_to_display.to_csv("events_to_display.csv")